# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_(self):
    self.driver.get("https://www.selenium.dev/selenium/web/web-form.html")
    self.driver.set_window_size(945, 1020)
    self.driver.find_element(By.ID, "my-text-id").click()
    self.driver.find_element(By.ID, "my-text-id").send_keys("홍길동")
    self.driver.find_element(By.NAME, "my-password").send_keys("0203")
    self.driver.find_element(By.NAME, "my-textarea").send_keys("나는 조선 제일의 검사다!")
    self.driver.find_element(By.NAME, "my-select").click()
    dropdown = self.driver.find_element(By.NAME, "my-select")
    dropdown.find_element(By.XPATH, "//option[. = 'Two']").click()
    self.driver.find_element(By.NAME, "my-datalist").click()
    self.driver.find_element(By.NAME, "my-datalist").send_keys("Chicago")
    self.driver.find_element(By.NAME, "my-colors").click()
    self.driver.find_element(By.NAME, "my-colors").send_keys("#261145")
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
