# -*- coding: utf-8 -*-
"""
Created on Mon Mar 25 11:43:48 2024

@author: Shin
"""
# Test 

# https://www.selenium.dev/selenium/web/web-form.html

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_(self):
    self.driver.get("https://www.selenium.dev/selenium/web/web-form.html")
    self.driver.set_window_size(800, 600)
    self.driver.find_element(By.ID, "my-text-id").click()
    self.driver.find_element(By.ID, "my-text-id").send_keys("신정윤")
    self.driver.find_element(By.NAME, "my-password").send_keys("0203")
    self.driver.find_element(By.NAME, "my-textarea").send_keys("This form is selenium-test code for learner")
    self.driver.find_element(By.NAME, "my-select").click()
    dropdown = self.driver.find_element(By.NAME, "my-select")
    dropdown.find_element(By.XPATH, "//option[. = 'Two']").click()
    self.driver.find_element(By.NAME, "my-datalist").click()
    self.driver.find_element(By.NAME, "my-datalist").send_keys("Chicago")
    self.driver.find_element(By.NAME, "my-colors").click()
    self.driver.find_element(By.NAME, "my-colors").send_keys("#261145")
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    
 #%%
# 클래스는 특정 개념을 표현만 할뿐 사용을 하려면 인스턴스를 생성해야함.
# 인스턴스 = 클래스()
test = Test()
# 메서드는 클래스가 아니라 인스턴스를 통해 호출합니다. 다음과 같이 인스턴스 뒤에 
#.(점)을 붙이고 메서드를 호출하면 됨.
# 인스턴스.메서드()
test.setup_method()
test.test_()


